@FirstCodeLab_HostAddress = http://localhost:5034

### 天氣預報
GET {{FirstCodeLab_HostAddress}}/weatherforecast/forecast
Accept: application/json

### 測試資料庫連線
POST {{FirstCodeLab_HostAddress}}/WeatherForecast/TestDBConnection
Accept: application/json

### 取得資料庫類型
GET {{FirstCodeLab_HostAddress}}/WeatherForecast/GetDbProviderName
Accept: application/json

### 新增 Customer: Alois
POST {{FirstCodeLab_HostAddress}}/customer/create
Accept: application/json
Content-Type: application/json

{
	"name": "Alois",
	"email": "alois@mail.server"
}

### 新增 Customer: John
POST {{FirstCodeLab_HostAddress}}/customer/create
Accept: application/json
Content-Type: application/json

{
	"name": "約翰",
	"email": "john@mail.server"
}

### 搜詢全部 Customer
POST {{FirstCodeLab_HostAddress}}/customer/search
Accept: application/json
Content-Type: application/json